# Generated by Django 3.1.7 on 2021-04-23 05:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('myapp', '0003_auto_20210423_0549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patron',
        ),
    ]
