# Generated by Django 3.1.7 on 2021-04-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210423_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patron',
            old_name='firts_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patron',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
